# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ed10b72644921b4b52f7b9b4aac8516045782eeb704f6b1dcee1ebc034c98096"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fc6fe4a8617bc978b2e459c54a4c8a4d98285ba481f7603a3078d570307201b"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Make a remote hub feel local: auto-sync cwd + remote tmux sessions over SSH"
  homepage "https://github.com/DigiBugCat/duck"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mutagen-io/mutagen/mutagen",
    ]

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
