# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "45f604fbc7763f53a066ac7fe976707d34256d341fe6c35136d0eabfa49517b7"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "16d970c815a48dee15c1b172d39e9e440356aae1c8e2814490c826e9bc3665cd"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Make a remote hub feel local: auto-sync cwd + remote tmux sessions over SSH"
  homepage "https://github.com/DigiBugCat/duck"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mutagen-io/mutagen/mutagen",
    ]

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
