# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6ea996c4cc4a461ec89be51d9e582e338b3a072c41075aa383aa5c1140c27fb7"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3bf047199ce3686ad44adc9bc643b0eeaeff03b4c423318d252fc644aee2626"
      url "https://github.com/DigiBugCat/duck/releases/download/v#{version}/duck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Make a remote hub feel local: auto-sync cwd + remote tmux sessions over SSH"
  homepage "https://github.com/DigiBugCat/duck"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mutagen-io/mutagen/mutagen",
    ]

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
